### ISSUE TITLE
Callback on LDtkField set?

### ISSUE THREAD

**Issue by 19lmyers** [Picalines/godot-ldtk-import-mono#5]
I discovered today that LDtkField cannot be used on a property that executes custom logic.
I don't know how trivial that would be to change, so here is my request:
I would like to be able to run a method of my choice when the LDtkField bound property is set by reimport, much like I can with Exported properties in Tool scripts.

**Comment by Picalines** [comment]
It is very easy to implement - I just need to remove the check for a non-auto property.

To be honest, I don’t remember why I added this restriction initially, so I want to run tests first

**Comment by Picalines** [comment]
The property must have both a getter and a setter, because that's what Godot requires. Their logic only runs with the Tool attribute

**Comment by Picalines** [comment]
To be clear: now non auto properties are not ignored by the plugin. I haven't added any callbacks

**Comment by 19lmyers** [comment]
Thank you!
