### ISSUE TITLE
Is there a way to access the World/Level bounds programmatically on import?

### ISSUE THREAD

**Issue by 19lmyers** [Picalines/godot-ldtk-import-mono#6]
Basically, I have an entity that I would like to overlap the entire world, but only the parts that exist in LDtk. 
Is there a way to access each level's bounds programmatically upon import?
This way I wouldn't have to put a Rect on top of my entire level.
(Alternatively, this could be part of some sort of support for post-import logic, linked to in the json?)

**Comment by Picalines** [comment]
`LDtkField("#size")` gives pixel size of entity/level. I would have something like this:
```cs
public class Level // for base level scene
{
    [LDtkField("#size")]
    public Vector2 Size { get; private set; }
}
```

But that's not enough to solve your problem. I will check LDtk docs, maybe it's possible to implement `#size` for some `World` class

**Comment by Picalines** [comment]
I *can* add something like:
```cs
LDtkImportPlugin.OnWorldImported += worldJson => { /* ... */ };
```

But I don't think it's a good design choice. I've used this setup in a few old game projects, and each time it resulted in strange code that, among other things, is very dependent on the current version of the addon/LDtk.

Shortly speaking, I would like to learn more about your use case

**Comment by 19lmyers** [comment]
Wait, I can attach a script to the base Level scene and use LDtkField in it? That solves all my problems!

For reference, my use case is that I'm rendering a grid of arrows on top of the level that visualize the local gravity at each tile, and I have entities that can change the local gravity in their bounds.

**Comment by Picalines** [comment]
I definitely need to update the README or add some tutorials 😅

Also from your description, I think you can use a tile entities (using json with "#entity" field in LDtk tileset you can replace tiles with Godot scenes). In my case I used it for different tile effects and things like level transition triggers. This is powerful with LDtk auto layers

**Comment by 19lmyers** [comment]
This is actually related to this issue so I'll just add it here. 
I know it's possible to access the level size, but is it possible to access the level position?
I've run into a problem where I need to translate level-local coordinates (LDtk Points are stored as this) to world-local coordinates.

**Comment by 19lmyers** [comment]
Wait, I'm stupid. Nevermind.

**Comment by Picalines** [comment]
Godot has `GlobalPosition` property or `ToGlobal/ToLocal` methods.

In my games I have used to create `Level` class and making that every entity inside a level can access it's instance. It's also would be useful for stuff with coordinates.

A little later I'll throw a couple of useful methods and classes here.

**Comment by Picalines** [comment]
I can't add these classes to the addon directly, because their implementation is not common to all projects. In some tutorial they would fit

```cs
public sealed partial class Level : Node2D
{
    // Here we can store references to layers and other stuff
    public Node2D EntitiesLayer { get; private set; } = null!;

    public override void _Ready()
    {
        base._Ready();

        EntitiesLayer = GetNode<Node2D>("Layers/Entities");
    }

    // This method is used to find Level instance in parent chain
    public static Level? GetOf(Node entityNode) => entityNode switch
    {
        Level level => level,
        Node when entity2D.GetParent() is Node parent => GetOf(parent),
        _ => null,
    }
}
```
```cs
public sealed partial class Level
{
    // This class can be used inside of Entity to easily access and change its level
    // ("change level" means to reassign its parents and keep the position)
    public sealed class EntityHandle
    {
        private readonly Node _EntityNode;

        private Level _Level;

        public EntityHandle(Node entityNode)
        {
            _EntityNode = entityNode;

            _Level = GetOf(entityNode) ?? throw new System.NullReferenceException();
        }

        public Level Level
        {
            get => _Level;
            set
            {
                if (_Level == value || _EntityNode.GetParent() is not Node entityParent)
                {
                    return;
                }

                // to keep Node2Ds position we store its GlobalPosition
                // and reassign it later
                Vector2 oldPosition = (_EntityNode as Node2D)?.GlobalPosition ?? Vector2.Zero;

                entityParent.RemoveChild(_EntityNode);

                _Level = value;
                _Level.EntitiesLayer.AddChild(_EntityNode);

                if (_EntityNode is Node2D entity2D)
                {
                    entity2D.GlobalPosition = oldPosition;
                }
            }
        }
    }

    public interface IEntity
    {
        EntityHandle EntityHandle { get; }
    }
}
```
Here is example usage of `EntityHandle`:
```cs
public sealed class Player : Node2D
{
    private Level.EntityHandle _EntityHandle;
    
    public override _Ready()
    {
        _EntityHandle = new(this);
        _EntityHandle.Level // ...
    }
}
```
